version: '3'
networks:
  banco:
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 139276
      POSTGRES_USER: 'admin'
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    container_name: todo_db
    networks:
      - banco
  api:
    build: .
    ports:
      - 3333:3333
      - 9229:9229
    container_name: todo_api
    networks:
      - banco
